version: "3.9"

services:
  whiteboard:
    build: .
    container_name: whiteboard_app
    ports:
      - "80:80"
    volumes:
      - dbdata:/var/www/html/data
    restart: unless-stopped

volumes:

  dbdata:
